name: Test code

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        go: ['1.19', '1.20']
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: test
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          cache: false

      - name: test
        run: go test ./...

      - name: race
        run: go test -race ./...
